# Site
title: "Luyao Niu"
title_separator: "-"
name: "Luyao Niu"
description: "Assistant Teaching Professor, Electrical & Computer Engineering, University of Washington"
url: https://luyaoniu.github.io
baseurl: ""
repository: "luyaoniu/luyaoniu.github.io"
locale: en-US
search: false
masthead_title: "Luyao Niu"

# Author / sidebar
author:
  name: "Luyao Niu"
  avatar: "profile.jpg"
  bio: "Assistant Teaching Professor, ECE, University of Washington."
  location: "Seattle, WA"
  email: "luyaoniu@uw.edu"
  googlescholar: "https://scholar.google.com/citations?user=nSFafMoAAAAJ&hl=en&oi=ao"

# Build
markdown: kramdown
highlighter: rouge
permalink: /:categories/:title/
timezone: America/Los_Angeles

# Plugins (only those allowed by GitHub Pages)
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from

# Include pages outside the default Jekyll source
include:
  - .htaccess
  - _pages

# Exclude from build
exclude:
  - Gemfile
  - Gemfile.lock
  - scripts/
  - docs/
  - vendor/
  - "*.log"

# Defaults
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
