"""Render mybib.bib into Jekyll _pages/publications.md and _data/featured_publications.yml.

Single source of truth: mybib.bib at the repo root. Re-run idempotently.
"""
from __future__ import annotations

import argparse
import re
from collections import OrderedDict
from pathlib import Path
from typing import Iterable

import bibtexparser
from bibtexparser.bparser import BibTexParser

AUTHOR_NAME = "Luyao Niu"  # The owner's name, to bold in author lists.

_TYPE_MAP = {
    "article": "Journal",
    "inproceedings": "Conference",
    "conference": "Conference",
    "incollection": "Conference",
    "misc": "Preprint",
    "unpublished": "Preprint",
    "techreport": "Preprint",
}


def parse_bib(path: Path) -> list[dict]:
    """Parse a .bib file into a list of entry dicts."""
    parser = BibTexParser(common_strings=True)
    parser.ignore_nonstandard_types = False
    with open(path, encoding="utf-8") as f:
        db = bibtexparser.load(f, parser=parser)
    return db.entries


def _entry_type_label(entry: dict) -> str:
    return _TYPE_MAP.get(entry.get("ENTRYTYPE", "misc").lower(), "Preprint")


def _entry_year(entry: dict) -> int:
    raw = entry.get("year", "0").strip()
    try:
        return int(re.search(r"\d{4}", raw).group(0))
    except (AttributeError, ValueError):
        return 0


def group_by_year_and_type(entries: Iterable[dict]) -> "OrderedDict[int, OrderedDict[str, list[dict]]]":
    """Group entries by year (desc) then by type (Journal, Conference, Preprint)."""
    type_order = ["Journal", "Conference", "Preprint"]
    bucket: dict[int, dict[str, list[dict]]] = {}
    for e in entries:
        y = _entry_year(e)
        t = _entry_type_label(e)
        bucket.setdefault(y, {}).setdefault(t, []).append(e)
    out: "OrderedDict[int, OrderedDict[str, list[dict]]]" = OrderedDict()
    for year in sorted(bucket.keys(), reverse=True):
        out[year] = OrderedDict(
            (t, bucket[year][t]) for t in type_order if t in bucket[year]
        )
    return out


def _normalize_name(raw: str) -> str:
    """Convert 'Last, First' to 'First Last'. Leave 'First Last' untouched."""
    raw = raw.strip()
    if "," in raw:
        last, first = (p.strip() for p in raw.split(",", 1))
        return f"{first} {last}"
    return raw


def render_authors(authors_field: str, equal_contrib: bool = False) -> str:
    """Render the BibTeX `author` field as a comma-separated list with the
    owner's name bolded. If equal_contrib, append `\\*` to the first two authors."""
    parts = [_normalize_name(a) for a in authors_field.split(" and ")]
    target = AUTHOR_NAME.strip()

    def bold_if_target(name: str) -> str:
        return f"**{name}**" if name == target else name

    rendered = [bold_if_target(p) for p in parts]
    if equal_contrib and len(rendered) >= 2:
        rendered[0] = rendered[0] + "\\*"
        rendered[1] = rendered[1] + "\\*"
    return ", ".join(rendered)


def render_links(entry: dict) -> str:
    """Render link badges from known fields. Returns a string of `[label](url)` separated by ` · `."""
    links: list[str] = []
    if doi := entry.get("doi"):
        links.append(f"[DOI](https://doi.org/{doi.strip()})")
    if url := entry.get("url"):
        label = "arXiv" if "arxiv.org" in url.lower() else "URL"
        links.append(f"[{label}]({url.strip()})")
    if pdf := entry.get("pdf"):
        links.append(f"[PDF]({pdf.strip()})")
    if code := entry.get("code"):
        links.append(f"[code]({code.strip()})")
    if project := entry.get("project"):
        links.append(f"[project]({project.strip()})")
    return " · ".join(links)


def _venue(entry: dict) -> str:
    return (entry.get("journal") or entry.get("booktitle") or entry.get("howpublished") or "").strip().replace("\n", " ").replace("\t", " ")


def _flag(entry: dict, key: str) -> bool:
    return str(entry.get(key, "")).strip().lower() == "true"


def render_publications_markdown(entries: list[dict]) -> str:
    """Render a Jekyll page grouping entries by year/type."""
    grouped = group_by_year_and_type(entries)
    any_equal = any(_flag(e, "equal_contrib") for e in entries)

    lines: list[str] = []
    lines.append("---")
    lines.append('permalink: /publications/')
    lines.append('title: "Publications"')
    lines.append("author_profile: true")
    lines.append("---")
    lines.append("")
    lines.append("<!-- AUTO-GENERATED by scripts/bib_to_publications.py. Edit mybib.bib, not this file. -->")
    lines.append("")
    if any_equal:
        lines.append("\\* indicates equal contribution")
        lines.append("")

    for year, types in grouped.items():
        lines.append(f"## {year}")
        lines.append("")
        for type_label, type_entries in types.items():
            lines.append(f"### {type_label}")
            lines.append("")
            for e in type_entries:
                authors = render_authors(e.get("author", ""), equal_contrib=_flag(e, "equal_contrib"))
                title = e.get("title", "").strip().strip("{}").replace("\n", " ")
                venue = _venue(e)
                year_str = e.get("year", "").strip()
                links = render_links(e)
                line = f"- {authors}. \"{title}.\""
                if venue:
                    line += f" *{venue}*,"
                line += f" {year_str}."
                if links:
                    line += f" {links}"
                lines.append(line)
            lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def render_featured_yaml(entries: list[dict]) -> str:
    """Render featured publications as a YAML list for the home page."""
    featured = [e for e in entries if _flag(e, "featured")]
    lines = ["# AUTO-GENERATED by scripts/bib_to_publications.py. Edit mybib.bib, not this file."]
    for e in featured:
        title = e.get("title", "").strip().strip("{}").replace("\n", " ").replace('"', '\\"')
        authors = render_authors(e.get("author", ""), equal_contrib=_flag(e, "equal_contrib"))
        venue = _venue(e).replace('"', '\\"')
        year = e.get("year", "").strip()
        links = render_links(e).replace('"', '\\"')
        lines.append(f'- title: "{title}"')
        lines.append(f'  authors: "{authors}"')
        lines.append(f'  venue: "{venue}"')
        lines.append(f'  year: "{year}"')
        lines.append(f'  links: "{links}"')
    return "\n".join(lines) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--bib", default="mybib.bib", help="Path to .bib file")
    ap.add_argument("--out-publications", default="_pages/publications.md")
    ap.add_argument("--out-featured", default="_data/featured_publications.yml")
    args = ap.parse_args()

    entries = parse_bib(Path(args.bib))
    Path(args.out_publications).parent.mkdir(parents=True, exist_ok=True)
    Path(args.out_featured).parent.mkdir(parents=True, exist_ok=True)
    Path(args.out_publications).write_text(render_publications_markdown(entries), encoding="utf-8")
    Path(args.out_featured).write_text(render_featured_yaml(entries), encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
